name: gestufincap
recipe: symfony
config:
  webroot: public
  php: 8.2
  ini:
    memory_limit: 4096M
    max_execution_time: 600
    post_max_size: 2048M

services:
  appserver:
    portforward: true
    overrides:
      ports:
        - '3777:80'
        - '4777:443'
  database:
    type: mysql
    portforward: true
    creds:
      user: lucas
      password: 5566
      database: gestufincap
  phpmyadmin:
    type: phpmyadmin
    depends_on:
      - database
    portforward: true

tooling:
  node:
    service: appserver
  npm:
    service: appserver
  yarn:
    service: appserver
